### ISSUE TITLE
Проблема с TCachedTextWriter

### ISSUE THREAD

**Issue by ruslancnua** [d-mozulyov/CachedBuffers#2]
(я нуб)
В общем пишу логи используя класс TCachedTextWriter, столкнулся с проблемой если диск переполнен вылетает  ошибка 112 "Недостаточно места на диске". При этом не могу коректно освободить обьект, т.к. ошибка повторно вылетает в Destroy.
 Cached := TCachedFileWriter.Create('F:\3');
  try

    while True do
    begin

      Cached.Write('asdasdasda', 10);

    end;
  finally

    Cached.Free;
  end;

**Comment by d-mozulyov** [comment]
Добрый день

Попробую исправить ошибку в ближайшие несколько дней

**Comment by d-mozulyov** [comment]
Я завёл отдельные ветки для рефакторинга трёх модулей:
https://github.com/d-mozulyov/UniConv/tree/feature/refactoring
https://github.com/d-mozulyov/CachedBuffers/tree/feature/refactoring
https://github.com/d-mozulyov/CachedTexts/tree/feature/refactoring

Просьба попробовать их в связке (!) и отписаться о результатах.

**Comment by ruslancnua** [comment]
Проблема с освовождением обьекта при недостатке свободного места решена.

**Comment by d-mozulyov** [comment]
@ruslancnua,

Отлично. Тогда сейчас всё закоммичу в master
